### ISSUE TITLE
关于部分规则存在些许问题

### ISSUE THREAD

**Issue by linfeng1649** [Noyllopa/NoAppDownload#1]
广告规则开发者你好，你的广告规则中关于哔哩哔哩的部分会使哔哩哔哩视频（google商店版本）加载速度过慢（甚至无法播放），请重新审核关于此部分规则

**Comment by Noyllopa** [comment]
你好，这个规则只标记了网页上的部分元素，没有涉及域名的解析，理应对视频加载速度没有影响。
如果你的问题仍然存在，请按照下列顺序排查：
1. 移除本规则中哔哩哔哩的部分或全部条目
2. 移除本规则
3. 更换广告屏蔽软件
如果尝试以上步骤 1 或步骤 2 后问题解决，说明本规则确实存在问题，请提供你的具体使用环境以便排查（使用的软件、机型、系统等）

**Comment by linfeng1649** [comment]
你好，依照上述部分在尝试步骤2后，问题得以解决。以下具体使用环境：
&nbsp; &nbsp; &nbsp;1.使用软件：adguard
&nbsp; &nbsp; &nbsp;2.使用机型：Mi6
&nbsp; &nbsp; &nbsp;3.系统MIUI 11.0.5
在多次尝试过程中，可以明确相应部分规则与哔哩哔哩app（Google play版）视频能否加载（常常表现为无法加载）存在关系，建议重新审核此部分规则。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Noyllopa/NoAppDownload"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月17日(星期三) 上午10:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Noyllopa/NoAppDownload] 关于部分规则存在些许问题 (Issue #1)





 
你好，这个规则只标记了网页上的部分元素，没有涉及域名的解析，理应对视频加载速度没有影响。
 如果你的问题仍然存在，请按照下列顺序排查：
  
移除本规则中哔哩哔哩的部分或全部条目
 
移除本规则
 
更换广告屏蔽软件
 如果尝试以上步骤 1 或步骤 2 后问题解决，说明本规则确实存在问题，请提供你的具体使用环境以便排查（使用的软件、机型、系统等）
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Noyllopa** [comment]
我这边使用了 play 版 bilibili，在安卓的 AdGuard 上测试了一天，未能复现

**Comment by linfeng1649** [comment]
你好，经过多次试验，可能是总体规则数目过多导致的，与该规则无关。抱歉，叨扰多时！
